### ISSUE TITLE
整合中的實體沒有作用

### ISSUE THREAD

**Issue by NelsPu** [osk2/panasonic_smart_app#101]
新年快樂
這幾天的除濕機F-Y20JH，在整合之中都會顯示不可用。
以下是截圖及Log顯示內容
<img width="250" alt="Snipaste_2024-02-14_10-47-10" src="https://github.com/osk2/panasonic_smart_app/assets/98749956/200ccf4b-d74c-4420-b643-0a8cbe426889">

2024-02-14 10:38:24.673 WARNING (MainThread) [homeassistant.components.humidifier.const] DEVICE_CLASS_DEHUMIDIFIER was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.675 WARNING (MainThread) [homeassistant.components.humidifier.const] SUPPORT_MODES was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.680 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.682 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_TEMPERATURE was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.684 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ENERGY was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.686 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM25 was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM25 instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.687 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.689 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.691 WARNING (MainThread) [homeassistant.const] TIME_MINUTES was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.699 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.701 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.703 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.705 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.707 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from panasonic_smart_app, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/osk2/panasonic_smart_app/issues
2024-02-14 10:38:24.717 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 453, in state_attributes
    raise ValueError(
ValueError: Entity sensor.chu_shi_ji_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured.

**Comment by TwKenYang** [comment]
搭版F-Y24GX同時也出現一樣的問題，看起來是python寫法更新，幾個不支援

**Comment by TwKenYang** [comment]
我成功解決了完全讀不到的問題
由於新版本的 Home Assistant 中不再需要last_reset的屬性
所以直接使用File editor
找到路徑/homeassistant/custom_components/panasonic_smart_app/sensor.py
其中290~292行註釋掉即可正常使用
![image](https://github.com/osk2/panasonic_smart_app/assets/122585150/2ef07cb4-6731-40e0-8903-ef354fdd5fcd)
以下是存檔後重啟
![OKAPP](https://github.com/osk2/panasonic_smart_app/assets/122585150/9117e388-3c7f-420e-b28b-a20a653b0806)
再期待開發者更新了^^

**Comment by NelsPu** [comment]
> ## 我成功解決了完全讀不到的問題
> 由於新版本的 Home Assistant 中不再需要last_reset的屬性
> 所以直接使用File editor
> 找到路徑/homeassistant/custom_components/panasonic_smart_app/sensor.py
> 其中291~293行註釋掉即可正常使用
> ![image](https://private-user-images.githubusercontent.com/122585150/305172932-2ef07cb4-6731-40e0-8903-ef354fdd5fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNjQwMTgsIm5iZiI6MTcwODA2MzcxOCwicGF0aCI6Ii8xMjI1ODUxNTAvMzA1MTcyOTMyLTJlZjA3Y2I0LTY3MzEtNDBlMC04OTAzLWVmMzU0ZmRkNWZjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwNjA4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2ZmNDJhYzAzNTBlZjVjZGEwZjUwMDZmODQ3MzNhOTYyNzk4MTZkMmY5YjkzNDcwZjRkZTJkNWE0MjU0MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SDVA2kOryclq0ew5XQS2vtrhG9-nXOQ5AjSWOKctlMg)
> 以下是存檔後重啟
> ![OKAPP](https://private-user-images.githubusercontent.com/122585150/305171959-9117e388-3c7f-420e-b28b-a20a653b0806.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNjQwMTgsIm5iZiI6MTcwODA2MzcxOCwicGF0aCI6Ii8xMjI1ODUxNTAvMzA1MTcxOTU5LTkxMTdlMzg4LTNjN2YtNDIwZS1iMjhiLWEyMGE2NTNiMDgwNi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwNjA4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGE2ZTM4NzhkOTM1MjIwYzk3MDBkOTk1YjRhYjk5MWE0OWU1ZDkzYjcyMmI3MjRiZDdhYjRiOGRjYjkxMTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yiiBi2e8PQVbVAPaiNsDoykIRQUaSEgcmV9zM8fezig)
> 再期待開發者更新了^^
> 另外補充一個 即將棄用的 supported features 警告 警告訊息說，套件中的除濕機使用即將在 Home Assistant Core 2025.1 中被移除的 supported features 值。Home Assistant 開發者建議改用 HumidifierEntityFeature.MODES。

非常感謝，照步驟操作已經解決問題
習慣自動化後，這幾天手動操作真的感覺超麻煩，感謝

同樣感謝開發者，期待更新

**Comment by RoadosW** [comment]
我的不在291～293
利用搜尋字串 def last_reset(self) 是在271～273

![image](https://github.com/osk2/panasonic_smart_app/assets/150249492/9882e817-ca60-48cb-99a9-e5e4d5a7366f)

**Comment by osk2** [comment]
下一版會修正這個問題，手動移除 `last_reset` 可以暫時解決這個問題
