### ISSUE TITLE
除濕機的實體顯示不可用！

### ISSUE THREAD

**Issue by Timyeh0211** [osk2/panasonic_smart_app#110]
除濕機的實體顯示不可用！
有照之前版友提供的做法將291至293註記掉，但是變成我的洗衣機不可用....
請問該如何解決呢 謝謝

![image](https://github.com/osk2/panasonic_smart_app/assets/173326897/654c9e13-2287-46cb-b2d4-480507173358)
![image](https://github.com/osk2/panasonic_smart_app/assets/173326897/d6888cb0-4444-40af-991d-224ad97cba14)
![image](https://github.com/osk2/panasonic_smart_app/assets/173326897/69407657-ccc4-4963-b340-88d9ba735813)
![image](https://github.com/osk2/panasonic_smart_app/assets/173326897/a4ba173d-2ecb-46fc-8328-37152c057bb1)
![image](https://github.com/osk2/panasonic_smart_app/assets/173326897/5d8d3862-f7c8-4124-9315-05a3e3e37946)

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 2024年6月5日 下午10:10:45 (2 occurrences)
Last logged: 上午11:00:42

Error while setting up panasonic_smart_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 361, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

**Comment by osk2** [comment]
方便提供機型跟 debug log 嗎？

**Comment by Timyeh0211** [comment]
> 方便提供機型跟 debug log 嗎？

F-Y20JH /  Log檔如下

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:423
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 下午1:08:04 (2 occurrences)
Last logged: 下午1:08:04

Entity sensor.chu_shi_ji_1_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/osk2/panasonic_smart_app/issues
Entity sensor.xi_yi_ji_1_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/osk2/panasonic_smart_app/issues
--------------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 下午1:08:04 (1 occurrences)
Last logged: 下午1:08:04

Error adding entities for domain sensor with platform panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 361, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range
--------------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 下午1:08:04 (1 occurrences)
Last logged: 下午1:08:04

Error while setting up panasonic_smart_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 361, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

**Comment by osk2** [comment]
[v2.8.2](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.8.2) 修正了一些除濕機的問題，再試試能不能正常運作

**Comment by Timyeh0211** [comment]
> [v2.8.2](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.8.2) 修正了一些除濕機的問題，再試試能不能正常運作

一樣不能用耶
![image](https://github.com/user-attachments/assets/3866ca16-cdd7-437e-8034-5813fe139ed6)
![image](https://github.com/user-attachments/assets/8f17d46c-bdd6-4831-bbab-035e572dedf3)

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 上午10:53:38 (2 occurrences)
Last logged: 下午12:42:36

Error adding entities for domain sensor with platform panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 368, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

--------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 上午10:53:38 (2 occurrences)
Last logged: 下午12:42:36

Error while setting up panasonic_smart_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 368, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

**Comment by JyunWei-Su** [comment]
有遇到類似問題，不過我這邊是warning不影響使用，不確定是不是 async_setup 的問題
```
WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration panasonic_smart_app with title: ****** and entry_id: 01J2S****************C143, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```

**Comment by JyunWei-Su** [comment]
@Timyeh0211 請問您的帳號下有洗衣機嗎，因為 sensor 的 log 是報錯在`洗衣機`，除濕機的實體可能要看一下`humidifier.py`的log。

> 一樣不能用耶
> Logger: homeassistant.components.sensor Source: helpers/entity_platform.py:507 Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) First occurred: 上午10:53:38 (2 occurrences) Last logged: 下午12:42:36
> 
> Error adding entities for domain sensor with platform panasonic_smart_app Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities await asyncio.gather(*tasks) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/config/custom_components/panasonic_smart_app/sensor.py", line 368, in state _current_status = list( ^^^^^ IndexError: list index out of range

**Comment by Timyeh0211** [comment]
有一台洗衣機~log檔如下再麻煩了謝謝!!
![image](https://github.com/user-attachments/assets/5186d4d6-b5b9-4b14-bc99-f4446327bbe0)

Logger: homeassistant.components.humidifier
Source: helpers/entity_platform.py:573
Integration: 加濕器 (documentation, issues)
First occurred: 2024年7月26日 上午10:53:46 (3 occurrences)
Last logged: 上午10:04:33

panasonic_smart_app: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 368, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

**Comment by JyunWei-Su** [comment]
不確定是不是 sensor.py 報錯導致除濕機實體沒辦法正常顯示，可以試試看修改 sensor.py 增加兩行，重啟後看問題能不能解決:
在`PanasonicWashingStatusSensor `底下的 `def state` 
```
        if not raw_mode_list:
            return STATE_UNAVAILABLE
``` 
修改後如下： 
```
    @property
    def state(self) -> int:
        status = self.coordinator.data[self.index]["status"]
        washing_status = status.get("0x50")

        if not washing_status:
            return STATE_UNAVAILABLE

        raw_mode_list = list(
            filter(lambda c: c["CommandType"] == "0x50", self.commands)
        )[0]["Parameters"]
        
        if not raw_mode_list:
            return STATE_UNAVAILABLE
        
        _current_status = list(
            filter(lambda m: m[1] == int(washing_status), raw_mode_list)
        )[0][0]
        
        _LOGGER.debug(f"[{self.label}] state: {_current_status}")
        return _current_status
```

**Comment by Timyeh0211** [comment]
感謝!!!可以了耶~~~~
但是PM2.5仍然無法顯示
這個要提供log檔嗎還是先更新到 v2.83?
![image](https://github.com/user-attachments/assets/f8ae3c20-4cf5-492a-adbf-1e27f6658ec4)
![image](https://github.com/user-attachments/assets/697c5eb1-39a6-4bcc-aab3-f567e4a67865)

**Comment by JyunWei-Su** [comment]
> 感謝!!!可以了耶~~~~ 但是PM2.5仍然無法顯示 這個要提供log檔嗎還是先更新到 v2.83?

PM2.5 的問題在 [2.8.3](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.8.3) 解決了，可以更新試試愾
