### ISSUE TITLE
除濕機實體又不可用了 !

### ISSUE THREAD

**Issue by timya0211** [osk2/panasonic_smart_app#123]
目前版本為 V2.8.5
HA 2024.1.6
目前僅有一台除濕機和洗衣機
再麻煩幫我看一下了謝謝

![image](https://github.com/user-attachments/assets/efd3f9ee-a791-4cc1-9a07-7ac9495557da)
![image](https://github.com/user-attachments/assets/8d596e19-85e4-4ac0-a5dd-ff4002934c5c)

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 上午11:24:17 (1 occurrences)
Last logged: 上午11:24:17

Error adding entities for domain sensor with platform panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 372, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 上午11:24:17 (1 occurrences)
Last logged: 上午11:24:17

Error while setting up panasonic_smart_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 372, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

Logger: homeassistant.components.humidifier
Source: helpers/entity_platform.py:573
Integration: 加濕器 ([documentation](https://www.home-assistant.io/integrations/humidifier), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+humidifier%22))
First occurred: 上午11:24:26 (1 occurrences)
Last logged: 上午11:24:26

panasonic_smart_app: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 372, in state
    _current_status = list(
                      ^^^^^
IndexError: list index out of range

**Comment by osk2** [comment]
請附上 debug log

**Comment by osk2** [comment]
Hi, 需要依照[這邊的](https://github.com/osk2/panasonic_smart_app/blob/master/README-zh.md#%E5%95%9F%E7%94%A8%E9%99%A4%E9%8C%AF%E7%B4%80%E9%8C%84)說明開啟 debug log 後才會有完整的紀錄，上傳前再注意一下紀錄可能會有帳號資訊，可以先移除後再上傳

**Comment by timya0211** [comment]
> Hi, 需要依照[這邊的](https://github.com/osk2/panasonic_smart_app/blob/master/README-zh.md#%E5%95%9F%E7%94%A8%E9%99%A4%E9%8C%AF%E7%B4%80%E9%8C%84)說明開啟 debug log 後才會有完整的紀錄，上傳前再注意一下紀錄可能會有帳號資訊，可以先移除後再上傳

是這個嗎?已有把帳密刪除了 謝謝
[home-assistant_panasonic_smart_app_2024-12-01T15-05-08.333Z.log](https://github.com/user-attachments/files/17969386/home-assistant_panasonic_smart_app_2024-12-01T15-05-08.333Z.log)

**Comment by osk2** [comment]
與 #122 相同，詳細說明如[連結](https://github.com/osk2/panasonic_smart_app/issues/122#issuecomment-2620770618)，會在下一版修正

**Comment by osk2** [comment]
v2.10.1 已經修正此問題
