### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by mrhsiao** [osk2/panasonic_smart_app#18]
Version: 1.3.0

更新完有點問題 也重新安裝過了 再麻煩作者幫忙看一下！感謝

Log:
Traceback (most recent call last):
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 155, in request
response = await self._session.request(
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
await resp.start(conn)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
self._continue = None
File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/panasonic_smart_app/__init__.py", line 43, in async_setup_entry
await client.login()
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 68, in login
response = await self.request(
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 48, in wrapper_call
results = await asyncio.gather(*[
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 159, in request
auth = headers["auth"]
KeyError: 'auth'

**Comment by osk2** [comment]
這錯誤不會影響正常使用，之後會再修復，這是登入時逾時導致的錯誤，可能原因有：
1. API 沒有回應
2. 超量使用被封鎖

先將整合停用也不要使用 app，隔幾分鐘後再重試一次看看

**Comment by mrhsiao** [comment]
還會出現這種錯誤

2021-07-15 23:00:06 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法將類型 'System.__ComObject' 的 COM 物件轉換為介面類型 'System.IDisposable'。由於發生下列錯誤，介面 (IID 為 '{805D7A98-D4AF-3F0F-967F-E5CF45312D2C}') 之 COM 元件上的 QueryInterface 呼叫失敗而導致作業失敗: RPC 伺服器無法使用。 (發生例外狀況於 HRESULT: 0x800706BA)。"}
2021-07-15 23:00:06 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mrhsiao29 for panasonic_smart_app

**Comment by mrhsiao** [comment]
我發現是如果在第一次建立 entry 如果有裝置是連上網路的時候，會導致執行錯誤

**Comment by osk2** [comment]
這錯誤也有人反應過，這是 Panasonic 伺服器出錯，我就無能為力了

**Comment by mrhsiao** [comment]
不過我把沒連線的裝置刪除了 entry還是沒辦法建立但是看log好像都正常

**Comment by osk2** [comment]
沒連線的裝置在設定和更新時都會被略過，要有更詳細的 log 才能看出問題在哪

照著下面的設定把 log 開到 debug 等級就可以了，但之後記得再復原，不然 log 檔會炸裂 😆 
https://github.com/osk2/panasonic_smart_app#enable-logs

**Comment by mrhsiao** [comment]
2021-07-16 11:31:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for panasonic_smart_app
Traceback (most recent call last):
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 155, in request
response = await self._session.request(
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
await resp.start(conn)
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
self._continue = None
File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/panasonic_smart_app/__init__.py", line 43, in async_setup_entry
await client.login()
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 68, in login
response = await self.request(
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 48, in wrapper_call
results = await asyncio.gather(*[
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 159, in request
auth = headers["auth"]
KeyError: 'auth'

**Comment by shiauy** [comment]
2021-07-16 21:30:56 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: 建立連接至 SQL Server 時，發生網路相關或執行個體特定的錯誤。找不到或無法存取伺服器。確認執行個名稱是否正確，以及 SQL Server 是否設定為允許遠端連線。 (provider: Named Pipes Provider, error: 40 - 無法開啟至 SQL Server 的連接)

請問這個錯誤如何解決，從1.2到1.31都還沒有成功進入伺服器

**Comment by osk2** [comment]
> 2021-07-16 21:30:56 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: 建立連接至 SQL Server 時，發生網路相關或執行個體特定的錯誤。找不到或無法存取伺服器。確認執行個名稱是否正確，以及 SQL Server 是否設定為允許遠端連線。 (provider: Named Pipes Provider, error: 40 - 無法開啟至 SQL Server 的連接)
> 
> 請問這個錯誤如何解決，從1.2到1.31都還沒有成功進入伺服器

這錯誤我剛剛測試時有遇到，這是 Panasonic 伺服器異常，app 也是無法登入，我這邊沒辦法做什麼處理

**Comment by osk2** [comment]
Fixed key error in 4c8aa6ab6d56560af3b9d2684f9b7d2650a4e315.

**Comment by osk2** [comment]
本 issue 中除了開頭回報的 `KeyError: 'auth'` 外都是 Panasonic 伺服器異常造成的，只能等他自己恢復正常了

keyError 的問題已在 v1.3.2 修復，可以再更新試試

**Comment by mrhsiao** [comment]
辛苦作者了 我都想努力看看python 了 感覺恨有趣😂
