### ISSUE TITLE
V.2.4.0 無法連線至裝置，將於下輪更新時重試 

### ISSUE THREAD

**Issue by yourender** [osk2/panasonic_smart_app#48]
安裝完輸入帳號密碼後會顯示 "重試設定中: None"然後出現"設定失敗"
Log如下:

自行安裝整合產生錯誤。

Logger: homeassistant.config_entries
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:262
Integration: Panasonic Smart App (documentation, issues)
First occurred: 21:55:54 (1 occurrences)
Last logged: 21:55:54

Error setting up entry xxxx@outlook.com for panasonic_smart_app
Traceback (most recent call last):
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 244, in request
    response = await self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/panasonic_smart_app/__init__.py", line 42, in async_setup_entry
    await client.login()
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 77, in login
    response = await self.request(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 58, in wrapper_call
    results = await asyncio.gather(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 262, in request
    raise PanasonicDeviceOffline(f"無法連線至裝置，將於下輪更新時重試")
custom_components.panasonic_smart_app.smartApp.exceptions.PanasonicDeviceOffline: 無法連線至裝置，將於下輪更新時重試

**Comment by osk2** [comment]
先試試把所有裝置上線再安裝能成功嗎？

**Comment by yourender** [comment]
裝置上線後重新安裝確認可以加入，洗衣機冷氣都可以看到狀態，太感謝了！
