### ISSUE TITLE
錯誤：無法連線至裝置，將於下輪更新時重試

### ISSUE THREAD

**Issue by nick3434** [osk2/panasonic_smart_app#49]
想請問osk2底下這個錯誤是屬於超量使用API的一種嗎？
近期這個問題滿常發生的...

發生後，冷氣溫度、耗電量等皆為unavailable，也無法開關機和設定。

我的冷氣是2021年式RX系列
Home Assistant OS 7.5
supervisor-2022.05.3
core-2022.4.5
Panasonic Smart App-v2.4.0

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:262
Integration: Panasonic Smart App (documentation, issues)
First occurred: May 28, 2022, 7:56:59 AM (1 occurrences)
Last logged: May 28, 2022, 7:56:59 AM

Error setting up entry xxxxxxx@mail.com for panasonic_smart_app
Traceback (most recent call last):
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 244, in request
    response = await self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/panasonic_smart_app/__init__.py", line 42, in async_setup_entry
    await client.login()
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 77, in login
    response = await self.request(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 58, in wrapper_call
    results = await asyncio.gather(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 262, in request
    raise PanasonicDeviceOffline(f"無法連線至裝置，將於下輪更新時重試")
custom_components.panasonic_smart_app.smartApp.exceptions.PanasonicDeviceOffline: 無法連線至裝置，將於下輪更新時重試

```

**Comment by osk2** [comment]
裝置的模組沒有連上伺服器，通常拔插頭重插就會恢復了
