### ISSUE TITLE
洗衣機的目前模式總是顯示不可用

### ISSUE THREAD

**Issue by coolalec** [osk2/panasonic_smart_app#54]
你好我的洗衣機是NA-V178DDH.
插件的版本是v2.4.0.

使用的時候發現洗衣機不論在哪個階段目前模式都是顯示不可用
如以下照片請參考, 洗衣機在脫水中, 但在HA上面還是顯示不可用
![Screenshot_20220625-090229](https://user-images.githubusercontent.com/9547520/175752860-6352b34b-1c42-4ec4-9029-0e904596c88c.png)
![未命名](https://user-images.githubusercontent.com/9547520/175752888-c15fc13c-d115-425d-8cf7-ce5c4e107c1f.png)

如果有需要提供更多資訊再麻煩告知, 謝謝

**Comment by osk2** [comment]
這我再來看看是什麼問題
我帳號內的洗衣機是跟網友借來的，要開發還要剛好等到對方洗衣服才能測試，這可能沒這麼快解決 😅

**Comment by coolalec** [comment]
如果有需要的話我可以提供我的帳號讓你測試.

**Comment by osk2** [comment]
@coolalec 我用 NA-V160HDH 測試起來洗衣 `目前模式` 是能正常讀取的，我在想可能跟不同的機型有關係

若你方便的話可以分享洗衣機給我測試，後續部分較隱私可直接用 mail 詳談，我的信箱是： osk2@osk2.me

![Screen Shot 2022-08-30 at 9 47 51 PM](https://user-images.githubusercontent.com/705280/187454615-2d3cea21-c359-4bad-98cd-63e1623e4ccb.png)

**Comment by osk2** [comment]
@coolalec 請問現在「目前模式」還會有顯示為不可用的情況嗎？這幾天稍微看了一下應該是可以正常顯示的

**Comment by coolalec** [comment]
還是一樣顯示不可用
另外目前行程似乎都是要等一段時間才會正常顯示, 不確定這樣是否正常?

![image](https://user-images.githubusercontent.com/9547520/194049395-1b9c9b29-7613-4880-a250-ca10e9ee42fd.png)

**Comment by osk2** [comment]
我會再檢查看看哪邊有問題

目前行程的更新時機應該會跟其他資訊一樣，如果只有目前行程會很等久才顯示的話就不太正常了

**Comment by 1043717432** [comment]
是否可以，在同胞下載大陸的APP和登陸大陸的賬號呢？？我很需要這款設備接入ha

**Comment by 3uperduck** [comment]
我的機型是NA-V190MDH 全部都撈不到資料 如果需要的話可以分享裝置 謝謝

<img width="503" alt="image" src="https://github.com/osk2/panasonic_smart_app/assets/52876446/ba221988-673d-4939-a611-b47fb948135a">

**Comment by osk2** [comment]
v2.10.1 有修正運轉狀態實體，可以試試看，如果還有問題再重新打開這個 issue

**Comment by coolalec** [comment]
@osk2 我很像沒有權限可以Reopen Issue, 先附上Log

記錄器: homeassistant.components.sensor
來源: helpers/entity_platform.py:927
整合: 感測器 ([相關文件](https://www.home-assistant.io/integrations/sensor), [問題](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
首次發生: 下午9:38:30 (1 事件)
最後紀錄: 下午9:38:30

Error adding entity sensor.gun_tong_xi_yi_ji_mu_qian_mo_shi for domain sensor with platform panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 524, in state
    _current_mode = list(
                    ~~~~~
        filter(lambda m: m[1] == int(mode), raw_mode_list)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    )[0][0]
    ~^^^
IndexError: list index out of range

**Comment by coolalec** [comment]
這是另一段Log, 看起來Root Cause是相同的

記錄器: homeassistant.components.sensor
來源: helpers/entity_platform.py:737
整合: 感測器 ([相關文件](https://www.home-assistant.io/integrations/sensor), [問題](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
首次發生: 下午9:38:30 (1 事件)
最後紀錄: 下午9:38:30

panasonic_smart_app: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 596, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 524, in state
    _current_mode = list(
                    ~~~~~
        filter(lambda m: m[1] == int(mode), raw_mode_list)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    )[0][0]
    ~^^^
IndexError: list index out of range

**Comment by osk2** [comment]
洗衣機當初只測試過一個型號，猜測不同型號的資料格式應該有差異，可以的話開啟 debug logging 後再附上日誌，方便我除錯

**Comment by coolalec** [comment]
看起來應該是我這台洗衣機的位址不同, 當初你測試的那個型號的目前模式的位址是0x54, 我這台是0x03.
({"CommandType":"0x03","CommandName":"工程訊息","ParameterType":"enum","ParameterUnit":"","Parameters":[["除垢",1],["浸泡",2],["洗衣",3],["洗清",4],["脫水",5],["乾衣",6],["送風",7],["鬆布",8],["冷卻",9],["nanoe",10],["延後晾衣",11],["槽除黴",12]]},)



我把const.py line 98, sensore.py line 512, line 516從0x54改成0x03.
就可以正常取得目前模式了.
再請幫忙看要怎麼改才可以同時相容不同型號的洗衣機.
謝謝.

![Image](https://github.com/user-attachments/assets/057276c9-534b-4472-a5dc-a5d1cccc3a0c)

**Comment by osk2** [comment]
感謝協助釐清，我後續會再調整
