### ISSUE TITLE
sensor狀態都是不可用，也沒有控制開關選項

### ISSUE THREAD

**Issue by jericho0711** [osk2/panasonic_smart_app#67]
家中三台冷氣整合產生錯誤，整合刪除停用二天以上，再重新登入app還是出現一樣的狀況，使用官方app正常，請問該如何處理?
日誌上顯示錯誤

Logger: homeassistant.components.climate
Source: custom_components/panasonic_smart_app/climate.py:80
Integration: 溫控 ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 17:55:21 (4 occurrences)
Last logged: 17:57:54

Error adding entities for domain climate with platform panasonic_smart_app
Error while setting up panasonic_smart_app platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 643, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 260, in capability_attributes
    supported_features = self.supported_features
  File "/config/custom_components/panasonic_smart_app/climate.py", line 80, in supported_features
    _swing_mode = CLIMATE_AVAILABLE_SWING_MODE[_raw_swing_mode]
KeyError: 65535

Logger: homeassistant.components.sensor
Source: custom_components/panasonic_smart_app/sensor.py:279
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17:55:21 (6 occurrences)
Last logged: 17:58:22

Error adding entities for domain sensor with platform panasonic_smart_app
Error while setting up panasonic_smart_app platform for sensor
panasonic_smart_app: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 279, in state
    return energy if energy >= 0 else STATE_UNAVAILABLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by osk2** [comment]
看起來是API回傳的數據格式異常，你家的是吊隱式冷氣嗎？

**Comment by jericho0711** [comment]
是的，吊隱式冷氣

**Comment by osk2** [comment]
我沒有吊隱式冷氣能測試，只能從你提供的 log 中嘗試修復問題

可以的話幫我載[這個版本](https://github.com/osk2/panasonic_smart_app/archive/refs/heads/fix/hanging-ac.zip)試試看能不能正常使用，沒問題的話我再正式發布更新

**Comment by jericho0711** [comment]
這個版本可以正常使用了，謝謝
