### ISSUE TITLE
一直顯示正在初始化

### ISSUE THREAD

**Issue by ivis0516** [osk2/panasonic_smart_app#80]
一直顯示正在初始化，刪掉再安裝也是一樣，本來可以用，刪掉重新安裝後就無法載入，請問一下有什麼辦法解決嗎？謝謝您

2023-07-26 10:16:48.563 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-26 10:16:48.564 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration panasonic_smart_app which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-26 10:16:48.564 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration taipower_bimonthly_cost which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-26 10:16:48.567 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration growatt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-26 10:16:48.567 ERROR (SyncWorker_3) [homeassistant.loader] The custom integration 'growatt' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2023-07-26 10:16:48.567 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-26 10:16:55.297 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-07-26 10:16:55.324 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store - 
2023-07-26 10:17:00.051 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_miot_raw: Integration not found.
2023-07-26 10:17:06.423 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.daily_net_production_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.427 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.daily_solar_powered_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.430 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.weekly_net_production_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.432 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.weekly_solar_powered_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.433 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.monthly_net_production_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.436 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.monthly_solar_powered_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.438 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.yearly_net_production_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:06.440 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.yearly_solar_powered_percentage (<class 'homeassistant.components.sense.sensor.SenseTrendsSensor'>) with state_class None has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+sense%22
2023-07-26 10:17:07.491 WARNING (MainThread) [custom_components.hacs] You have 'timvancann/homeassistant-growatt' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Integration is missing a version, and is abandoned.)
2023-07-26 10:18:37.781 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:18:55.187 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:18:55.189 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:18:55.194 WARNING (MainThread) [homeassistant.config_entries] Config entry '0927002511' for panasonic_smart_app integration not ready yet: None; Retrying in background
2023-07-26 10:19:22.393 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:19:40.202 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:21:55.248 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:22:12.750 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:25:48.124 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:26:05.756 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:26:05.757 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:27:48.269 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:28:06.367 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:28:06.369 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:29:48.193 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:30:05.697 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:30:05.698 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:33:46.781 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:34:05.059 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:34:05.061 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:39:39.287 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:39:44.887 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:40:02.209 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:40:02.210 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:40:20.900 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:40:37.159 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140654517469136] Error handling message: Unknown error (unknown_error) elvishung from fe80::401:9f73:c09f:e3f7 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 682, in websocket_get_translations
    resources = await async_get_translations(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 318, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 209, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 230, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'xiaomi_miot_raw' not found.
2023-07-26 10:40:39.001 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:40:39.002 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:41:41.117 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:41:43.915 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:41:58.430 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:41:58.431 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:42:01.129 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 417: {"State":"fail","StateMsg":"無法透過CommandId取得Commmand"}
2023-07-26 10:42:01.130 ERROR (MainThread) [custom_components.panasonic_smart_app] Error fetching Panasonic Smart Application data: Failed while updating device status
2023-07-26 10:43:18.611 INFO (MainThread) [custom_components.panasonic_smart_app] 
      Loading your Panasonic devices. This may takes few minutes to complete.

> @osk2 代為刪除重複及敏感資訊

**Comment by osk2** [comment]
log 中有帳號相關資訊先代為移除了

這看起來是帳號內有離線裝置，設定套件時先將所有裝置連線試試

**Comment by ivis0516** [comment]
謝謝你，問題解決了，真的是有一台斷線
